README.md
config/config.go
config/config_test.go
service/service.go

Added bucket, Aws region ,encryption disabled, vault address, vault token and vault path fields to the config.go file
Updated config_test.go file to check for the changes made
updated comments in the service.go file
Check the values for the fields added is correct

Added bucket and AWS region config to the new service

---

LICENSE.md
Makefile
README.md
policy.hcl

Added script in makefile to generate vault token for the service. This is added to make it easier for the devs when running the service
Check if the additions are correct
Anyone

Added script to generate vault token for the service in makefile

---

upload/upload.go

Rename function to indicate its an S3 related error and not a general thing.
Added error report to add context to logs, to aid debug publishing code.
Visual inspect.
Anyone.

Rename function. Add extra error reports to understand context.

---

Makefile
api/upload.go
api/upload_test.go
features/steps/steps.go
features/steps/upload_component.go
features/uploading_a_file.feature
files/store.go
files/store_test.go
go.mod
go.sum

Multipart upload

---

features/steps/steps.go
features/uploading_a_file.feature

Ensuring that all content makes it into the s3 bucket in component tests

---

docker-compose-local.yml
docker-compose.yml
encryption/key.go
features/steps/crypto.go
features/steps/external.go
features/steps/steps.go
features/steps/upload_component.go
features/uploading_a_file.feature
files/store.go
files/store_test.go
main_test.go
service/initialise.go
service/interfaces.go
service/mock_initialiser.go
service/service.go
service/service_test.go

Encrypt file and store encryption key in vault (Happy Path)

---

swagger.yaml

Documenting the new upload endpoint

---

Makefile
config/config.go
docker-compose-local.yml
docker-compose-services.yml
docker-compose.yml
service/initialise.go

Docker and Dependency Injection changes required to run smoke tests again this and dp-files-api

---

Makefile
api/upload_test.go
config/config.go
config/config_test.go
docker-compose-local.yml
features/steps/steps.go
files/store.go
service/service.go

Remove environment variable setting in the `Makefile` which was overriding environment configuration in `docker-compose`.
Run `docker-compose up` locally and ensure that services and dependencies come up correctly and can be tested using commands in the `README.md`.
Anyone

Smoketest setup

---

features/steps/steps.go
features/uploading_a_file.feature
files/store.go
files/store_test.go

Call to mark upload complete somewhat changed due to PATCH call with status UPLOADED payload

updated calls to files api in line with changes to RESTIFY

---

api/upload.go
api/upload_test.go
features/steps/steps.go
features/uploading_a_file.feature

change continue based on RFC only 100 if header in request
change continue otherwise to 200, complete to 201

Fix continue breaking gateway 502 issue

---

api/upload.go
api/upload_test.go
features/optional_collection_id.feature
files/store.go

Make collection ID optional

---

api/upload.go
ci/lint.yml
ci/scripts/lint.sh

Adjust max multipart memory to chunk size + 1MB

---

files/store.go

Using dp-net/http to make requests to dp-files-api

---

swagger.yaml

Updated doc to indicate the required fields, and give more description, especially on the meaning, requirements and constraints of fields.
Swagger docs only

Updated doc to indicate the required fields, and give more description

---

README.md

Documenting the API Client

---

README.md

Updating Copyright

---

go.mod
go.sum
upload/upload.go
upload/upload_test.go

To resolve prod issues where Florence has stopped sending the query parameter, where that query parameter seems redundant anyway
Do the tests pass?
Does it compile?
Does it solve the problem? (Do uploads complete on the Dataset tab in Florence)
@mr-nick17

Check for query param or path fragment in GetS3URL

---

docker-compose-services.yml
features/optional_collection_id.feature
features/uploading_a_file.feature
files/store.go
files/store_test.go

On upload, fetch the etag of the whole object and not just the last uploaded part.
Eyeball
Anyone

fix etags on upload

---

swagger.yaml

- Added swagger.yml file to the root directory
- Added upload-new endpoint instructions
- Check if the Endpoint details make sense
- Optionally, you can import the .yaml file into postman and check if the request templates are loaded properly
@anyone

updated swagger.yml with OpenAI 2.0 standards

---

features/uploading_a_file.feature
files/store.go

Change database update location
Changes ok. Tests pass.
Anyone

Guard register file

---

files/store_test.go

Add unit tests for changes made in this PR - https://github.com/ONSdigital/dp-upload-service/pull/83
Changes make sense, tests pass
Anyone

add unit tests

---

dp-upload-service.nomad

As per title
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.

Ensure deployments spread over availability zones

---

Dockerfile.concourse

Amend Dockerfile.concourse to use ubuntu22 image as requested by the platform team.
Check updated image name with whats in CI elastic container registry.
Anyone.

Upgrade to ubuntu22

---

Dockerfile
Dockerfile.local
Dockerfile.test
Makefile
ci/audit.yml
ci/build.yml
ci/lint.yml
ci/unit.yml

- Switch to dis-vulncheck and bump Go version
- Check release is ok
Anyone

switch to vulncheck and bump go version
